openapi: 3.0.0
info:
  title: Your API
  version: 1.0.0
paths:
  /api/validate/xml:
    post:
      summary: Validate XML invoice
      description: Validate invoice in XML format and return errors as a JSON file.
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/Invoice'
      responses:
        '200':
          description: Successful validation
          content:
            application/json:
              example:
                successful: true
                firedAssertionErrors:
                  AUNZ_PEPPOL_1_1_10: []
                  AUNZ-UBL_1_1_10: []
        '400':
          description: Bad Request - Invalid XML data
          content:
            application/json:
              example:
                successful: false
                reason: 'XML not valid'
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                message: 'Internal server error. (Should not happen, but just in case it does)'
      headers:
        Content-Type: application/xml

  /api/generate/html:
    post:
      summary: Generate HTML version of the invoice
      description: Generate an HTML representation of the invoice.
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/Invoice'
      responses:
        '200':
          description: Successful HTML generation
          content:
            text/html:
              example: |
                <!DOCTYPE html>
                <html lang="en">
                <head>
                    <meta charset="UTF-8">
                    <meta http-equiv="X-UA-Compatible" content="IE=edge">
                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                    <title>Invoice HTML</title>
                </head>
                <body>
                    <!-- Your HTML content goes here -->
                    <h1>Your invoice: </h1>
                    <textarea rows="25" cols="150">
                        <!-- Include the XML content here -->
                    </textarea>
                    <h1>Output</h1>
                    Your schema was validated against the following two documents:
                    <div>AUNZ-PEPPOL-validation.sch</div>
                    <div>AUNZ-UBL-validation.sch</div>
                    (These documents were taken from: 
                    <a target="_blank" href="https://github.com/A-NZ-PEPPOL/A-NZ-PEPPOL-BIS-3.0/tree/master/Validation%20documents">here</a>)
                    <h2>Errors</h2>
                    <!-- Include error details here -->
                </body>
                </html>
        '400':
          description: Bad Request - Invalid invoice data
          content:
            application/json:
              example:
                successful: false
                reason: 'Invalid invoice data'
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                message: 'Internal server error. (Should not happen, but just in case it does)'
      headers:
        Content-Type: application/xml

  /api/generate/pdf:
    post:
      summary: Generate PDF version of the invoice
      description: Generate a PDF representation of the invoice.
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/Invoice'
      responses:
        '200':
          description: Successful PDF generation
          content:
            application/pdf:
              example: '<PDF content here>'
        '400':
          description: Bad Request - Invalid invoice data
          content:
            application/json:
              example:
                successful: false
                reason: 'Invalid invoice data'

# ... (rest of the file remains unchanged)



components:
  schemas:
    Invoice:
      type: object
      properties:
        CustomizationID:
          type: string
        ProfileID:
          type: string
        ID:
          type: string
        IssueDate:
          type: string
          format: date
        DueDate:
          type: string
          format: date
        InvoiceTypeCode:
          type: string
        Note:
          type: string
        DocumentCurrencyCode:
          type: string
        AccountingCost:
          type: string
        BuyerReference:
          type: string
        InvoicePeriod:
          $ref: '#/components/schemas/InvoicePeriod'
        OrderReference:
          $ref: '#/components/schemas/OrderReference'
        BillingReference:
          $ref: '#/components/schemas/BillingReference'
        DespatchDocumentReference:
          $ref: '#/components/schemas/DocumentReference'
        ReceiptDocumentReference:
          $ref: '#/components/schemas/DocumentReference'
        OriginatorDocumentReference:
          $ref: '#/components/schemas/DocumentReference'
        ContractDocumentReference:
          $ref: '#/components/schemas/DocumentReference'
        AccountingSupplierParty:
          $ref: '#/components/schemas/Party'
        AccountingCustomerParty:
          $ref: '#/components/schemas/Party'
        PayeeParty:
          $ref: '#/components/schemas/Party'
        TaxRepresentativeParty:
          $ref: '#/components/schemas/Party'
        Delivery:
          $ref: '#/components/schemas/Delivery'
        PaymentMeans:
          $ref: '#/components/schemas/PaymentMeans'
        PaymentTerms:
          $ref: '#/components/schemas/PaymentTerms'
        AllowanceCharge:
          $ref: '#/components/schemas/AllowanceCharge'
        TaxTotal:
          $ref: '#/components/schemas/TaxTotal'
        LegalMonetaryTotal:
          $ref: '#/components/schemas/LegalMonetaryTotal'
        InvoiceLine:
          type: array
          items:
            $ref: '#/components/schemas/InvoiceLine'

    InvoicePeriod:
      type: object
      properties:
        StartDate:
          type: string
          format: date
        EndDate:
          type: string
          format: date

    OrderReference:
      type: object
      properties:
        ID:
          type: string
        SalesOrderID:
          type: string

    BillingReference:
      type: object
      properties:
        InvoiceDocumentReference:
          $ref: '#/components/schemas/DocumentReference'

    DocumentReference:
      type: object
      properties:
        ID:
          type: string
        IssueDate:
          type: string
          format: date

    Party:
      type: object
      properties:
        EndpointID:
          type: string
        PartyIdentification:
          $ref: '#/components/schemas/PartyIdentification'
        PartyName:
          $ref: '#/components/schemas/PartyName'
        PostalAddress:
          $ref: '#/components/schemas/PostalAddress'
        PartyTaxScheme:
          $ref: '#/components/schemas/PartyTaxScheme'
        PartyLegalEntity:
          $ref: '#/components/schemas/PartyLegalEntity'
        Contact:
          $ref: '#/components/schemas/Contact'

    PartyIdentification:
      type: object
      properties:
        ID:
          type: string

    PartyName:
      type: object
      properties:
        Name:
          type: string

    PostalAddress:
      type: object
      properties:
        StreetName:
          type: string
        AdditionalStreetName:
          type: string
        CityName:
          type: string
        PostalZone:
          type: string
        Country:
          $ref: '#/components/schemas/Country'

    Country:
      type: object
      properties:
        IdentificationCode:
          type: string

    PartyTaxScheme:
      type: object
      properties:
        CompanyID:
          type: string
        TaxScheme:
          $ref: '#/components/schemas/TaxScheme'

    TaxScheme:
      type: object
      properties:
        ID:
          type: string

    PartyLegalEntity:
      type: object
      properties:
        RegistrationName:
          type: string
        CompanyID:
          type: string
        CompanyLegalForm:
          type: string

    Contact:
      type: object
      properties:
        Name:
          type: string
        Telephone:
          type: string
        ElectronicMail:
          type: string

    Delivery:
      type: object
      properties:
        ActualDeliveryDate:
          type: string
          format: date
        DeliveryLocation:
          $ref: '#/components/schemas/DeliveryLocation'
        DeliveryParty:
          $ref: '#/components/schemas/Party'

    DeliveryLocation:
      type: object
      properties:
        ID:
          type: string
        Address:
          $ref: '#/components/schemas/PostalAddress'

    PaymentMeans:
      type: object
      properties:
        PaymentMeansCode:
          type: object
          properties:
            name:
              type: string
          example: "Credit transfer"
        PaymentID:
          type: string
        PayeeFinancialAccount:
          $ref: '#/components/schemas/PayeeFinancialAccount'

    PayeeFinancialAccount:
      type: object
      properties:
        ID:
          type: string
        Name:
          type: string
        FinancialInstitutionBranch:
          $ref: '#/components/schemas/FinancialInstitutionBranch'

    FinancialInstitutionBranch:
      type: object
      properties:
        ID:
          type: string

    PaymentTerms:
      type: object
      properties:
        Note:
          type: string

    AllowanceCharge:
      type: object
      properties:
        ChargeIndicator:
          type: boolean
        AllowanceChargeReasonCode:
          type: string
        AllowanceChargeReason:
          type: string
        MultiplierFactorNumeric:
          type: number
        Amount:
          type: number
        BaseAmount:
          type: number
        TaxCategory:
          $ref: '#/components/schemas/TaxCategory'

    TaxCategory:
      type: object
      properties:
        ID:
          type: string
        Percent:
          type: number
        TaxScheme:
          $ref: '#/components/schemas/TaxScheme'

    TaxTotal:
      type: object
      properties:
        TaxAmount:
          type: number
        TaxSubtotal:
          $ref: '#/components/schemas/TaxSubtotal'

    TaxSubtotal:
      type: object
      properties:
        TaxableAmount:
          type: number
        TaxAmount:
          type: number
        TaxCategory:
          $ref: '#/components/schemas/TaxCategory'

    LegalMonetaryTotal:
      type: object
      properties:
        LineExtensionAmount:
          type: number
        TaxExclusiveAmount:
          type: number
        TaxInclusiveAmount:
          type: number
        ChargeTotalAmount:
          type: number
        PrepaidAmount:
          type: number
        PayableAmount:
          type: number

    InvoiceLine:
      type: object
      properties:
        ID:
          type: string
        Note:
          type: string
        InvoicedQuantity:
          $ref: '#/components/schemas/InvoicedQuantity'
        LineExtensionAmount:
          type: number
        AccountingCost:
          type: string
        InvoicePeriod:
          $ref: '#/components/schemas/InvoicePeriod'
        OrderLineReference:
          $ref: '#/components/schemas/OrderLineReference'
        DocumentReference:
          $ref: '#/components/schemas/DocumentReference'
        Item:
          $ref: '#/components/schemas/Item'
        Price:
          $ref: '#/components/schemas/Price'

    InvoicedQuantity:
      type: object
      properties:
        unitCode:
          type: string
        value:
          type: number

    OrderLineReference:
      type: object
      properties:
        LineID:
          type: string

    Item:
      type: object
      properties:
        Description:
          type: string
        Name:
          type: string
        BuyersItemIdentification:
          $ref: '#/components/schemas/BuyersItemIdentification'
        SellersItemIdentification:
          $ref: '#/components/schemas/SellersItemIdentification'
        StandardItemIdentification:
          $ref: '#/components/schemas/StandardItemIdentification'
        OriginCountry:
          $ref: '#/components/schemas/Country'
        CommodityClassification:
          $ref: '#/components/schemas/CommodityClassification'
        ClassifiedTaxCategory:
          $ref: '#/components/schemas/ClassifiedTaxCategory'

    BuyersItemIdentification:
      type: object
      properties:
        ID:
          type: string

    SellersItemIdentification:
      type: object
      properties:
        ID:
          type: string

    StandardItemIdentification:
      type: object
      properties:
        ID:
          type: string
        schemeID:
          type: string

    CommodityClassification:
      type: object
      properties:
        ItemClassificationCode:
          $ref: '#/components/schemas/ItemClassificationCode'

    ItemClassificationCode:
      type: object
      properties:
        listID:
          type: string
        value:
          type: string

    ClassifiedTaxCategory:
      type: object
      properties:
        ID:
          type: string
        Percent:
          type: number
        TaxScheme:
          $ref: '#/components/schemas/TaxScheme'

    Price:
      type: object
      properties:
        PriceAmount:
          type: number
        AllowanceCharge:
          $ref: '#/components/schemas/AllowanceCharge'
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Z5450330/API-validation/1.0.0